### ISSUE TITLE
django-pardakht as a django-payments variant

### ISSUE THREAD

**Issue by MRdevX** [ARKhoshghalb/django-pardakht#1]
Hi Dear Alireza,
thanks for this great job, django-pardakht is really helpful for implementing Iranian gateways in Django Web Apps :)
I have some kind of issue, i hope you could help me with:
I'm trying to Implement Django-Pardakht gateways in [Saleor E-Commerce Software](http://getsaleor.com/) which uses [Django-Payments](https://github.com/mirumee/django-payments).

Django-Payment supports some backends which described in the [docs](https://django-payments.readthedocs.io/en/latest/modules.html).

It would be great if django-pardakht could be implemented as one of django-payments variants.
because i don't want to break saleor's payment functionality.

I was wondering if you'd mind helping me through it?
Thanks in Advance.

**Comment by Ali-Toosi** [comment]
Hi,
I will check out Django-Payments in order to use django-pardakht for Iranian gateways in it, and will come back to you with results in a week.

**Comment by MRdevX** [comment]
Thanks, that would be great.

**Comment by dinamycam** [comment]
i would  be looking forward to that, as well.
i'm using saleor for a project, too; so if any help was needed, i would be more than happy to help.
it's my job any way:))

**Comment by MRdevX** [comment]
@ARKhoshghalb Hi Alireza, did you checked it out?
@pouya-barzegar it would be great, let me informed if you done something about it.

**Comment by Ali-Toosi** [comment]
@MR612 I have been too busy in recent days. I will as soon as possible...

**Comment by dinamycam** [comment]
@MR612 
@ARKhoshghalb 
https://github.com/pouya-barzegar/django-payments
i tried to add zarinpal to django-payments, it doesn't throw any errors at me, and doesn't work yet,
but maybe we can track down where the problem lies in my code.

in your settings.py you edit checkout choices to:
CHECKOUT_PAYMENT_CHOICES = [
    ('zarinpal', 'زرین پال'),
...
]
and also in payment variants, zarinpal like this:
PAYMENT_VARIANTS = {
    'default': ('payments.dummy.DummyProvider', {}),
    'zarinpal': ('saleor.payment.ZarinpalProvider', {
        'merchant_code': 'XXXXXX-XXXX-XXXX-XXXXXXXXXX',
    })
}

whereas for testing, you can copy the zarinpal folder, from my fork of django-payments to somewhere like saleor/payment/ and change the address in PAYMENT_VARIANTS accordingly.
if you could get it working, or anything, contact me.

**Comment by dinamycam** [comment]
now it works :+1:
